project:
  type: book
  output-dir: docs

book:
  title: "The mini test book"
  subtitle: "TBD"
  author:
    - name: 
      - G. Alexi Rodríguez-Arelis
      email: alexrod@stat.ubc.ca
      attributes:
        corresponding: true
    - name: 
      - Kate Manskaia
      email: email@ubc.ca
    - name: 
      - Payman Nickchi
      email: payman.nickchi@ubc.ca
  date: today
  sidebar: 
    background: "#FCF3CF"
    search: true
    page-navigation: true

  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    number-depth: 1

editor: visual

