project:
  type: book
  output-dir: docs

book:
  title: "The Mini Test Book"
  subtitle: "(in development)"
  author:
    - name: 
      - G. Alexi Rodríguez-Arelis
      email: alexrod@stat.ubc.ca
      attributes:
        corresponding: true
    - name: 
      - Kate Manskaia
      email: email@ubc.ca
    - name: 
      - Payman Nickchi
      email: payman.nickchi@ubc.ca
  date: today
  abstract: "This mini-book presents fundamental hypothesis tests in statistical inference using different mind maps while incorporating a common test workflow. We utilize `Python` and `R` in parallel to demonstrate the execution of these tests."
  keyword: statistical inference, statistical analysis, hypothesis testing, frequentist statistics
  url: https://pnickchi.github.io/test-book/
  sidebar: 
    background: "#FAB964"
    logo: img/toolkit.png
    search: true
  site-url: https://pnickchi.github.io/test-book/
  repo-url: https://github.com/pnickchi/test-book
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  page-footer: 
    left: |
      Copyright 2025; G. Alexi Rodríguez-Arelis, Kate Manskaia, and Payman Nickchi \
      <a href="https://www.flaticon.com/free-icon/toolkit_4229807?term=tool+box&page=1&position=24&origin=tag&related_id=4229807" title="toolkit icons">Toolkit icon created by Freepik - Flaticon</a>
  page-navigation: true
  navbar:
    search: true
    foreground: "#5ADBFF"
    background: "#094074"

  chapters:
    - index.qmd
    - book/privacy-policy.qmd
    - book/intro.qmd
    - book/chapter1.qmd
    - book/chapter2.qmd
    - book/chapter3.qmd
    - book/references.qmd

bibliography: book/references.bib

format:
  html:
    theme: cosmo
    css: custom.css
    fontsize: 1.2em
    linestretch: 1.65
    toc: true
    toc-location: right
    toc-depth: 4
    toc-title: The tools
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    code-link: true
    html-math-method: mathjax
    linkcolor: rgb(214, 122, 127)
    number-sections: true
    number-depth: 3
    grid:
      sidebar-width: 300px
      body-width: 960px
      margin-width: 275px
      gutter-width: 1.2em

  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex
