<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>2&nbsp; Tests for One Continuous Population Mean – The Mini Test Book (in development)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../book/chapter3-two-pop.html" rel="next">
<link href="../book/chapter1-intro.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f664b88e837a53bca78c5b20234386e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script><script src="../site_libs/quarto-diagram/mermaid-init.js"></script><link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../custom.css">
</head>
<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">The Mini Test Book (in development)</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <a href="https://github.com/pnickchi/test-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../book/chapter2-one-pop.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Tests for One Continuous Population Mean</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../img/toolkit.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none"></a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/meet-the-authors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Meet the Authors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/privacy-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Website Privacy Policy</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/chapter1-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/chapter2-one-pop.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Tests for One Continuous Population Mean</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/chapter3-two-pop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Tests for Two Continuous Population Mean</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/chapter4-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">ANOVA-related Tests for <span class="math inline">\(k\)</span> Continuous Population Means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/chapter5-chi-square.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chi-squared Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/A-greek-alphabet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Greek Alphabet</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/B-simulated-datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Simulated Datasets</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">The content</h2>
   
  <ul>
<li>
<a href="#one-sample-t-test-for-the-mean" id="toc-one-sample-t-test-for-the-mean" class="nav-link active" data-scroll-target="#one-sample-t-test-for-the-mean"><span class="header-section-number">2.1</span> One-sample t-test for the mean</a>
  <ul>
<li><a href="#review" id="toc-review" class="nav-link" data-scroll-target="#review"><span class="header-section-number">2.1.1</span> Review</a></li>
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design"><span class="header-section-number">2.1.2</span> Study design</a></li>
  <li><a href="#data-collection-and-wrangling" id="toc-data-collection-and-wrangling" class="nav-link" data-scroll-target="#data-collection-and-wrangling"><span class="header-section-number">2.1.3</span> Data Collection and Wrangling</a></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda"><span class="header-section-number">2.1.4</span> Exploratory Data Analysis (EDA)</a></li>
  <li><a href="#testing-settings" id="toc-testing-settings" class="nav-link" data-scroll-target="#testing-settings"><span class="header-section-number">2.1.5</span> Testing Settings</a></li>
  <li><a href="#hypothesis-definitions" id="toc-hypothesis-definitions" class="nav-link" data-scroll-target="#hypothesis-definitions"><span class="header-section-number">2.1.6</span> Hypothesis Definitions</a></li>
  <li><a href="#test-flavour-and-components" id="toc-test-flavour-and-components" class="nav-link" data-scroll-target="#test-flavour-and-components"><span class="header-section-number">2.1.7</span> Test Flavour and Components</a></li>
  <li><a href="#inferential-conclusions" id="toc-inferential-conclusions" class="nav-link" data-scroll-target="#inferential-conclusions"><span class="header-section-number">2.1.8</span> Inferential Conclusions</a></li>
  <li><a href="#how-to-run-the-test-in-r-and-python" id="toc-how-to-run-the-test-in-r-and-python" class="nav-link" data-scroll-target="#how-to-run-the-test-in-r-and-python"><span class="header-section-number">2.1.9</span> How to run the test in R and Python?</a></li>
  <li><a href="#storytelling" id="toc-storytelling" class="nav-link" data-scroll-target="#storytelling"><span class="header-section-number">2.1.10</span> Storytelling</a></li>
  </ul>
</li>
  <li>
<a href="#one-sample-z-test-for-the-mean" id="toc-one-sample-z-test-for-the-mean" class="nav-link" data-scroll-target="#one-sample-z-test-for-the-mean"><span class="header-section-number">2.2</span> One-sample z-test for the mean</a>
  <ul>
<li><a href="#review-1" id="toc-review-1" class="nav-link" data-scroll-target="#review-1"><span class="header-section-number">2.2.1</span> Review</a></li>
  <li><a href="#study-design-1" id="toc-study-design-1" class="nav-link" data-scroll-target="#study-design-1"><span class="header-section-number">2.2.2</span> Study Design</a></li>
  <li><a href="#data-collection-wrangling" id="toc-data-collection-wrangling" class="nav-link" data-scroll-target="#data-collection-wrangling"><span class="header-section-number">2.2.3</span> Data Collection &amp; Wrangling</a></li>
  <li><a href="#exploratory-data-analysis-eda-1" id="toc-exploratory-data-analysis-eda-1" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda-1"><span class="header-section-number">2.2.4</span> Exploratory Data Analysis (EDA)</a></li>
  <li><a href="#testing-settings-1" id="toc-testing-settings-1" class="nav-link" data-scroll-target="#testing-settings-1"><span class="header-section-number">2.2.5</span> Testing Settings</a></li>
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses"><span class="header-section-number">2.2.6</span> Hypotheses</a></li>
  <li><a href="#test-flavour-and-components-1" id="toc-test-flavour-and-components-1" class="nav-link" data-scroll-target="#test-flavour-and-components-1"><span class="header-section-number">2.2.7</span> Test Flavour and Components</a></li>
  <li><a href="#inferential-conclusions-1" id="toc-inferential-conclusions-1" class="nav-link" data-scroll-target="#inferential-conclusions-1"><span class="header-section-number">2.2.8</span> Inferential Conclusions</a></li>
  <li><a href="#how-to-run-the-test-in-r-and-python-1" id="toc-how-to-run-the-test-in-r-and-python-1" class="nav-link" data-scroll-target="#how-to-run-the-test-in-r-and-python-1"><span class="header-section-number">2.2.9</span> How to run the test in R and Python?</a></li>
  <li><a href="#storytelling-1" id="toc-storytelling-1" class="nav-link" data-scroll-target="#storytelling-1"><span class="header-section-number">2.2.10</span> Storytelling</a></li>
  </ul>
</li>
  <li>
<a href="#one-sample-z-test-for-proportions" id="toc-one-sample-z-test-for-proportions" class="nav-link" data-scroll-target="#one-sample-z-test-for-proportions"><span class="header-section-number">2.3</span> One-sample z-test for proportions</a>
  <ul>
<li><a href="#review-2" id="toc-review-2" class="nav-link" data-scroll-target="#review-2"><span class="header-section-number">2.3.1</span> Review</a></li>
  <li><a href="#study-design-2" id="toc-study-design-2" class="nav-link" data-scroll-target="#study-design-2"><span class="header-section-number">2.3.2</span> Study Design</a></li>
  <li><a href="#data-collection-wrangling-1" id="toc-data-collection-wrangling-1" class="nav-link" data-scroll-target="#data-collection-wrangling-1"><span class="header-section-number">2.3.3</span> Data Collection &amp; Wrangling</a></li>
  <li><a href="#exploratory-data-analysis-eda-2" id="toc-exploratory-data-analysis-eda-2" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda-2"><span class="header-section-number">2.3.4</span> Exploratory Data Analysis (EDA)</a></li>
  <li><a href="#hypotheses-1" id="toc-hypotheses-1" class="nav-link" data-scroll-target="#hypotheses-1"><span class="header-section-number">2.3.5</span> Hypotheses</a></li>
  <li><a href="#how-to-run-the-test-in-r-and-python-2" id="toc-how-to-run-the-test-in-r-and-python-2" class="nav-link" data-scroll-target="#how-to-run-the-test-in-r-and-python-2"><span class="header-section-number">2.3.6</span> How to run the test in R and Python</a></li>
  <li><a href="#inferential-conclusions-2" id="toc-inferential-conclusions-2" class="nav-link" data-scroll-target="#inferential-conclusions-2"><span class="header-section-number">2.3.7</span> Inferential Conclusions</a></li>
  <li><a href="#storytelling-2" id="toc-storytelling-2" class="nav-link" data-scroll-target="#storytelling-2"><span class="header-section-number">2.3.8</span> Storytelling</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/pnickchi/test-book/edit/main/book/chapter2-one-pop.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/pnickchi/test-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/pnickchi/test-book/blob/main/book/chapter2-one-pop.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-one-continuous-mean" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Tests for One Continuous Population Mean</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><!-- Google tag (gtag.js) --><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-DZWGQVJSHE"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DZWGQVJSHE');
</script><div class="LO">
<div class="LO-header">
<p>Learning Objectives</p>
</div>
<div class="LO-container">
<p>By the end of this chapter, you should be able to:</p>
<ul>
<li><p>Formulate hypotheses for testing a single population mean or proportion.</p></li>
<li><p>Choose and conduct an appropriate one-sample <code>t-test</code> or one-sample <code>z-test</code> based on study context and assumptions.</p></li>
<li><p>Differentiate between cases where the population variance is known and unknown, and select the appropriate test for each case.</p></li>
<li><p>Perform one-sample <code>t-tests</code> and <code>z-tests</code> using both <code>R</code> and <code>Python</code>, and interpret the outputs.</p></li>
<li><p>Apply statistical reasoning to real-world data examples, including evaluating assumptions and limitations.</p></li>
</ul>
</div>
</div>
<p>This chapter introduces statistical tests for analyzing a single sample, a common task in data analysis across many disciplines. These methods are used when we want to compare a sample-based estimate to a known or hypothesized population value. For example, we may want to test whether the average recovery time after a treatment differs from a clinical standard, whether student test scores exceed a benchmark, or whether the proportion of successes in a group differs from an expected rate. In each case, hypothesis testing helps us assess whether the observed difference is large enough to provide evidence against the null hypothesis, or whether it could reasonably be explained by random sampling variation.</p>
<div id="fig-test-chapter-1-mindmap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-test-chapter-1-mindmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"></figure><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Frequentist
  Hypothesis 
  Testings
  ))
    Simulation Based&lt;br/&gt;Tests
    Classical&lt;br/&gt;Tests
      (Chapter 1: &lt;br/&gt;Tests for One&lt;br/&gt;Continuous&lt;br/&gt;Population Mean)
        {{Unbounded&lt;br/&gt;Response}}
          Known&lt;br/&gt;Population&lt;br/&gt;Variance
            )One sample&lt;br/&gt;t test(
          Unknown&lt;br/&gt;Population&lt;br/&gt;Variance
            )One sample&lt;br/&gt;z test(
        {{Proportion between&lt;br/&gt;0 and 1&lt;br/&gt;obtained from a &lt;br/&gt;Binary Response}}
          )One sample&lt;br/&gt;z test(
      (Chapter 2: &lt;br/&gt;Tests for Two&lt;br/&gt;Continuous&lt;br/&gt;Population Means)
      (Chapter 3: &lt;br/&gt;ANOVA-related &lt;br/&gt;Tests for&lt;br/&gt;k Continuous&lt;br/&gt;Population Means)
</pre>
</div>
<p></p>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-test-chapter-1-mindmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: A specific hypothesis testing mind map outlining the techniques explored in this chapter, which are classical tests for one continuous population mean.
</figcaption></figure>
</div>
<p>In this chapter, we review tests for making inference about a single population parameter based on one sample. We focus on two common settings:</p>
<ul>
<li>A population mean, where the response variable is continuous, and</li>
<li>A population proportion, where the response variable is binary.</li>
</ul>
<p>For a single population mean, the choice of test depends on whether the population variance is known or unknown. When the population variance is unknown, we use the one-sample <code>t-test</code>. When the population variance is known, we use the one-sample <code>z-test</code>. For binary outcomes, we use a one-sample proportion <code>z-test</code> to compare the population proportion to a hypothesized value.</p>
<p>The choice of test depends on the type of response variable, the information available about the population variance, and the sample size. Each section below introduces the test setup, hypotheses, assumptions, theoretical background, and implementation in both <code>R</code> and <code>Python</code> using real or simulated data.</p>
<section id="one-sample-t-test-for-the-mean" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="one-sample-t-test-for-the-mean">
<span class="header-section-number">2.1</span> One-sample t-test for the mean</h2>
<section id="review" class="level3" data-number="2.1.1"><h3 data-number="2.1.1" class="anchored" data-anchor-id="review">
<span class="header-section-number">2.1.1</span> Review</h3>
<p>Use this test when:</p>
<ul>
<li>You have <strong>one sample</strong> from a population.</li>
<li>The response variable is <strong>quantitative</strong> (also known as <strong>continuous</strong>).</li>
<li>You want to test whether the population mean is equal to a specific reference value.</li>
<li>The population variance is <strong>unknown</strong>.</li>
<li>The sample is approximately normal, or the sample size is large enough for the sampling distribution of the sample mean to be approximately normal.</li>
</ul>
<p>In this section, we focus on the case where the population variance is unknown. The known-variance case will be discussed later using the one-sample <code>z-test</code>.</p>
<p>The one-sample <code>t-test</code> is used when we want to compare a sample mean to a hypothesized population mean. Suppose we observe a random sample of size <span class="math inline">\(n\)</span>,</p>
<p><span class="math display">\[
X_1, X_2, \dots, X_n,
\]</span></p>
<p>from a population with unknown mean <span class="math inline">\(\mu\)</span>. We want to assess whether the data provide enough evidence to conclude that <span class="math inline">\(\mu\)</span> differs from a specified reference value, denoted by <span class="math inline">\(\mu_0\)</span>.</p>
<p>The main statistical question is:</p>
<blockquote class="blockquote">
<p><strong>Is the population mean statistically different from the hypothesized value <span class="math inline">\(\mu_0\)</span>?</strong></p>
</blockquote>
<p>For example, if the hypothesized value is <span class="math inline">\(\mu_0 = 200\)</span>, then the question becomes:</p>
<blockquote class="blockquote">
<p><strong>Does the sample provide evidence that the population mean is different from 200?</strong></p>
</blockquote>
<p>Because the population variance is unknown, we estimate it using the sample standard deviation. This additional uncertainty is why the test statistic follows a <code>t-distribution</code> rather than a standard normal distribution.</p>
</section><section id="study-design" class="level3" data-number="2.1.2"><h3 data-number="2.1.2" class="anchored" data-anchor-id="study-design">
<span class="header-section-number">2.1.2</span> Study design</h3>
<p>Now that we have reviewed the general idea behind the one-sample <code>t-test</code>, let us apply it to a real data example. In this section, we use the <code>penguins</code> data set from the <code>palmerpenguins</code> package in <code>R</code>. This data set contains measurements for penguins observed near Palmer Station, Antarctica. Some of the main quantitative variables include <code>flipper_length_mm</code>, which records the length of a penguin’s flipper in millimetres; <code>bill_length_mm</code>, which records the length of the penguin’s bill in millimetres; <code>bill_depth_mm</code>, which records the depth or thickness of the bill in millimetres; and <code>body_mass_g</code>, which records the penguin’s body mass in grams.</p>
<p>For this example, the response variable of interest is <code>flipper_length_mm</code>, which records penguin flipper length in millimetres. We treat the observed penguins in the data set as a sample from a broader population of similar penguins. Let <span class="math inline">\(\mu\)</span> denotes the population mean flipper length of penguins. Suppose we want to compare the population mean flipper length to a reference value of 200 mm. In other words, we want to assess whether the sample provides evidence that the average flipper length in the population is different from 200 mm.</p>
<p>The main statistical question is:</p>
<blockquote class="blockquote">
<p><strong>Does the data provide evidence that the population mean flipper length of penguins is different from 200 mm?</strong></p>
</blockquote>
<p>In this example, the hypothesized population mean is</p>
<p><span class="math display">\[
\mu_0 = 200.
\]</span></p>
<p>To keep the exploratory and inferential parts of the analysis separate, we will split the data into a training set and a test set. The training set will be used for exploratory data analysis, and the test set will be used to conduct the formal hypothesis test.</p>
</section><section id="data-collection-and-wrangling" class="level3" data-number="2.1.3"><h3 data-number="2.1.3" class="anchored" data-anchor-id="data-collection-and-wrangling">
<span class="header-section-number">2.1.3</span> Data Collection and Wrangling</h3>
<p>To answer this question, we obtain the <code>penguins</code> data set from the <code>palmerpenguins</code> package. Note that we treat these data as a sample from a broader population of similar penguins. First, we create a new copy of the data set to avoid modifying the original data directly. This step is optional but it is a good habit when preparing data for analysis from datasets in <code>R</code> packages.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Get a copy of the data set</span></span>
<span><span class="va">penguins_data</span> <span class="op">&lt;-</span> <span class="va">penguins</span></span>
<span></span>
<span><span class="co"># Keep variables used in this section and remove missing values</span></span>
<span><span class="va">penguins_data</span> <span class="op">&lt;-</span> <span class="va">penguins_data</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span></span>
<span>    <span class="va">species</span>,</span>
<span>    <span class="va">island</span>,</span>
<span>    <span class="va">bill_length_mm</span>,</span>
<span>    <span class="va">bill_depth_mm</span>,</span>
<span>    <span class="va">flipper_length_mm</span>,</span>
<span>    <span class="va">body_mass_g</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">tidyr</span><span class="fu">::</span><span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the penguins data set and create a copy</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>penguins_data <span class="op">=</span> sns.load_dataset(<span class="st">"penguins"</span>).copy()</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep variables used in this section and remove missing values</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>penguins_data <span class="op">=</span> penguins_data[</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    [</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"species"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">"island"</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"bill_length_mm"</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"bill_depth_mm"</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"flipper_length_mm"</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"body_mass_g"</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>].dropna()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Finally, we randomly create training and test sets from this data set, using an 80-20 split. The training set will be used for exploratory data analysis, while the test set will be reserved for the formal one-sample <code>t-test</code>.</p>
<p>Because penguin species differ in their physical measurements, it is helpful to keep the proportion of species similar across the training and test sets. Otherwise, one set may contain relatively more penguins from a species with naturally longer or shorter flippers, which could affect the analysis. We therefore stratify the split by <code>species</code>.</p>
<div class="Heads-up">
<div class="Heads-up-header">
<p>Quick review!</p>
</div>
<div class="Heads-up-container">
<p>Although both <code>R</code> and <code>Python</code> allow us to set a random seed, <code>set.seed(42)</code> in <code>R</code> and <code>random_state = 42</code> in <code>Python</code> do not generally produce the same random split. This is because the two languages use different random number generators and different splitting algorithms. To make the results from <code>R</code> and <code>Python</code> directly comparable, we create the training and test sets once in <code>R</code> and then pass those same data sets to the Python code.</p>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Set seed for reproducibility</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Randomly split into training and testing sets, stratified by species</span></span>
<span><span class="va">penguins_split</span> <span class="op">&lt;-</span> <span class="fu">rsample</span><span class="fu">::</span><span class="fu"><a href="https://rsample.tidymodels.org/reference/initial_split.html">initial_split</a></span><span class="op">(</span></span>
<span>  <span class="va">penguins_data</span>,</span>
<span>  prop <span class="op">=</span> <span class="fl">0.8</span>,</span>
<span>  strata <span class="op">=</span> <span class="va">species</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Assign observations to training and testing sets</span></span>
<span><span class="va">train_set</span> <span class="op">&lt;-</span> <span class="fu">rsample</span><span class="fu">::</span><span class="fu"><a href="https://rsample.tidymodels.org/reference/initial_split.html">training</a></span><span class="op">(</span><span class="va">penguins_split</span><span class="op">)</span></span>
<span><span class="va">test_set</span>  <span class="op">&lt;-</span> <span class="fu">rsample</span><span class="fu">::</span><span class="fu"><a href="https://rsample.tidymodels.org/reference/initial_split.html">testing</a></span><span class="op">(</span><span class="va">penguins_split</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Sanity check</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Training shape:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">train_set</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training shape: 272 6 </code></pre>
</div>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Testing shape:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">test_set</span><span class="op">)</span>, <span class="st">"\n\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Testing shape: 70 6 </code></pre>
</div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Training species proportions:\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training species proportions:</code></pre>
</div>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">train_set</span><span class="op">$</span><span class="va">species</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Adelie Chinstrap    Gentoo 
0.4411765 0.1985294 0.3602941 </code></pre>
</div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"\nTesting species proportions:\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Testing species proportions:</code></pre>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">test_set</span><span class="op">$</span><span class="va">species</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Adelie Chinstrap    Gentoo 
0.4428571 0.2000000 0.3571429 </code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the training and test sets created in the R chunk</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>train_set <span class="op">=</span> r.train_set.copy()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>test_set <span class="op">=</span> r.test_set.copy()</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Sanity check</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training shape:"</span>, train_set.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training shape: (272, 6)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Testing shape:"</span>, test_set.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Testing shape: (70, 6)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Training species proportions:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Training species proportions:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(train_set[<span class="st">"species"</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>species
Adelie       0.441176
Gentoo       0.360294
Chinstrap    0.198529
Name: proportion, dtype: float64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Testing species proportions:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Testing species proportions:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(test_set[<span class="st">"species"</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>species
Adelie       0.442857
Gentoo       0.357143
Chinstrap    0.200000
Name: proportion, dtype: float64</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>The species proportions in the training and test sets are quite similar. For example, Adelie penguins make up about 44% of both sets, Chinstrap penguins about 20%, and Gentoo penguins about 36%. This suggests that the stratified split worked as intended and that the two sets have comparable species.</p>
</section><section id="exploratory-data-analysis-eda" class="level3" data-number="2.1.4"><h3 data-number="2.1.4" class="anchored" data-anchor-id="exploratory-data-analysis-eda">
<span class="header-section-number">2.1.4</span> Exploratory Data Analysis (EDA)</h3>
<p>Before conducting the formal hypothesis test, we use the training set to explore the distribution of <code>flipper_length_mm</code>. Since the one-sample <code>t-test</code> is used for a quantitative response variable, we first examine the center, spread, and overall shape of the flipper length distribution.</p>
<p>We begin by computing summary statistics for <code>flipper_length_mm</code> in the training set.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">train_set</span><span class="op">$</span><span class="va">flipper_length_mm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  174.0   190.0   197.0   201.1   214.0   231.0 </code></pre>
</div>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">train_set</span><span class="op">$</span><span class="va">flipper_length_mm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.01351</code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(train_set[<span class="st">"flipper_length_mm"</span>].describe())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>count    272.000000
mean     201.073529
std       14.013506
min      174.000000
25%      190.000000
50%      197.000000
75%      214.000000
max      231.000000
Name: flipper_length_mm, dtype: float64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Standard deviation:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Standard deviation:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(train_set[<span class="st">"flipper_length_mm"</span>].std())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>14.013505532620483</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>The summary statistics give us an initial sense of the typical flipper length and the amount of variability in the training data. In the training set, flipper lengths range from 174 mm to 231 mm. The sample mean is about 201.1 mm, while the median is 197 mm. The sample standard deviation is about 14.0 mm, indicating that flipper lengths vary noticeably across penguins. Since the hypothesized value in this section is 200 mm, the training-set mean appears close to the reference value. However, the formal test will be conducted later using the test set.</p>
<p>Next, we visualize the distribution of flipper lengths using a histogram. This helps us assess whether the data are approximately symmetric and whether there are unusual observations.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">train_set</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">flipper_length_mm</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">20</span>, color <span class="op">=</span> <span class="st">"black"</span>, fill <span class="op">=</span> <span class="st">"skyblue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Distribution of Flipper Length in the Training Set"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Flipper length (mm)"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Frequency"</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="chapter2-one-pop_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>plt.hist(</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    train_set[<span class="st">"flipper_length_mm"</span>],</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    bins<span class="op">=</span><span class="dv">20</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    edgecolor<span class="op">=</span><span class="st">"black"</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of Flipper Length in the Training Set"</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Flipper length (mm)"</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="chapter2-one-pop_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The histogram shows that the distribution of flipper length is not perfectly bell-shaped. Instead, it appears to have more than one cluster, with many observations around 190–200 mm and another group around 210–220 mm. This suggests that the overall distribution may be influenced by differences among penguin species. Although the distribution is not exactly normal, it does not show extreme skewness or severe outliers. Since the sample size is reasonably large, the one-sample <code>t-test</code> may still be appropriate due to the central limit theorem.</p>
<p>We can also use a Q-Q plot to compare the distribution of flipper lengths to a normal distribution. If the points roughly follow a straight line, this suggests that the normality assumption is not seriously violated.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">train_set</span>, <span class="fu">aes</span><span class="op">(</span>sample <span class="op">=</span> <span class="va">flipper_length_mm</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_qq</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_qq_line</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Q-Q Plot of Flipper Length in the Training Set"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Theoretical quantiles"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Sample quantiles"</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="chapter2-one-pop_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>stats.probplot(</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    train_set[<span class="st">"flipper_length_mm"</span>],</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    dist<span class="op">=</span><span class="st">"norm"</span>,</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    plot<span class="op">=</span>plt</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>((array([-2.80127058, -2.50184659, -2.33205435, -2.21092661, -2.11553933,
       -2.0362317 , -1.96798137, -1.9078294 , -1.85387981, -1.80484178,
       -1.75979524, -1.71806029, -1.67911976, -1.64257067, -1.60809269,
       -1.57542677, -1.54436037, -1.51471678, -1.48634749, -1.45912641,
       -1.43294553, -1.40771158, -1.38334345, -1.35977016, -1.33692918,
       -1.31476515, -1.29322882, -1.27227616, -1.25186762, -1.23196759,
       -1.21254382, -1.19356706, -1.17501065, -1.15685027, -1.1390636 ,
       -1.12163017, -1.10453114, -1.08774909, -1.07126792, -1.05507272,
       -1.03914963, -1.02348574, -1.00806902, -0.99288825, -0.97793292,
       -0.96319317, -0.94865978, -0.93432404, -0.9201778 , -0.90621335,
       -0.89242341, -0.87880113, -0.86534   , -0.85203388, -0.83887693,
       -0.82586361, -0.81298867, -0.80024711, -0.78763416, -0.77514529,
       -0.76277616, -0.75052265, -0.7383808 , -0.72634685, -0.71441718,
       -0.70258833, -0.69085698, -0.67921994, -0.66767417, -0.65621673,
       -0.64484479, -0.63355563, -0.62234665, -0.61121533, -0.60015923,
       -0.589176  , -0.5782634 , -0.56741923, -0.55664138, -0.54592781,
       -0.53527654, -0.52468565, -0.51415329, -0.50367766, -0.49325701,
       -0.48288966, -0.47257395, -0.46230828, -0.45209111, -0.44192091,
       -0.43179623, -0.42171561, -0.41167766, -0.40168103, -0.39172438,
       -0.38180641, -0.37192586, -0.36208149, -0.35227208, -0.34249646,
       -0.33275345, -0.32304193, -0.31336079, -0.30370892, -0.29408527,
       -0.28448878, -0.27491841, -0.26537316, -0.25585203, -0.24635404,
       -0.23687821, -0.22742362, -0.2179893 , -0.20857435, -0.19917786,
       -0.18979891, -0.18043664, -0.17109015, -0.16175858, -0.15244108,
       -0.1431368 , -0.13384489, -0.12456452, -0.11529487, -0.10603511,
       -0.09678444, -0.08754204, -0.07830712, -0.06907886, -0.05985649,
       -0.05063921, -0.04142622, -0.03221676, -0.02301002, -0.01380523,
       -0.00460161,  0.00460161,  0.01380523,  0.02301002,  0.03221676,
        0.04142622,  0.05063921,  0.05985649,  0.06907886,  0.07830712,
        0.08754204,  0.09678444,  0.10603511,  0.11529487,  0.12456452,
        0.13384489,  0.1431368 ,  0.15244108,  0.16175858,  0.17109015,
        0.18043664,  0.18979891,  0.19917786,  0.20857435,  0.2179893 ,
        0.22742362,  0.23687821,  0.24635404,  0.25585203,  0.26537316,
        0.27491841,  0.28448878,  0.29408527,  0.30370892,  0.31336079,
        0.32304193,  0.33275345,  0.34249646,  0.35227208,  0.36208149,
        0.37192586,  0.38180641,  0.39172438,  0.40168103,  0.41167766,
        0.42171561,  0.43179623,  0.44192091,  0.45209111,  0.46230828,
        0.47257395,  0.48288966,  0.49325701,  0.50367766,  0.51415329,
        0.52468565,  0.53527654,  0.54592781,  0.55664138,  0.56741923,
        0.5782634 ,  0.589176  ,  0.60015923,  0.61121533,  0.62234665,
        0.63355563,  0.64484479,  0.65621673,  0.66767417,  0.67921994,
        0.69085698,  0.70258833,  0.71441718,  0.72634685,  0.7383808 ,
        0.75052265,  0.76277616,  0.77514529,  0.78763416,  0.80024711,
        0.81298867,  0.82586361,  0.83887693,  0.85203388,  0.86534   ,
        0.87880113,  0.89242341,  0.90621335,  0.9201778 ,  0.93432404,
        0.94865978,  0.96319317,  0.97793292,  0.99288825,  1.00806902,
        1.02348574,  1.03914963,  1.05507272,  1.07126792,  1.08774909,
        1.10453114,  1.12163017,  1.1390636 ,  1.15685027,  1.17501065,
        1.19356706,  1.21254382,  1.23196759,  1.25186762,  1.27227616,
        1.29322882,  1.31476515,  1.33692918,  1.35977016,  1.38334345,
        1.40771158,  1.43294553,  1.45912641,  1.48634749,  1.51471678,
        1.54436037,  1.57542677,  1.60809269,  1.64257067,  1.67911976,
        1.71806029,  1.75979524,  1.80484178,  1.85387981,  1.9078294 ,
        1.96798137,  2.0362317 ,  2.11553933,  2.21092661,  2.33205435,
        2.50184659,  2.80127058]), array([174, 176, 178, 178, 178, 179, 180, 180, 180, 180, 181, 181, 181,
       181, 181, 182, 183, 183, 184, 184, 184, 184, 184, 185, 185, 185,
       185, 185, 185, 186, 186, 186, 186, 186, 186, 187, 187, 187, 187,
       187, 187, 187, 187, 187, 187, 187, 187, 187, 188, 188, 188, 188,
       189, 189, 189, 189, 189, 189, 190, 190, 190, 190, 190, 190, 190,
       190, 190, 190, 190, 190, 190, 190, 190, 190, 190, 190, 191, 191,
       191, 191, 191, 191, 191, 191, 191, 191, 191, 191, 191, 192, 192,
       192, 192, 192, 193, 193, 193, 193, 193, 193, 193, 193, 193, 193,
       193, 194, 194, 194, 194, 195, 195, 195, 195, 195, 195, 195, 195,
       195, 195, 195, 195, 195, 195, 196, 196, 196, 196, 196, 196, 196,
       196, 197, 197, 197, 197, 197, 197, 197, 197, 197, 198, 198, 198,
       198, 198, 198, 198, 199, 199, 199, 199, 199, 199, 200, 200, 200,
       201, 201, 201, 201, 201, 201, 202, 202, 203, 203, 203, 203, 203,
       205, 205, 208, 208, 208, 208, 208, 208, 208, 209, 209, 209, 210,
       210, 210, 210, 210, 210, 210, 210, 210, 210, 211, 212, 212, 212,
       212, 213, 213, 213, 213, 213, 213, 214, 214, 214, 214, 214, 215,
       215, 215, 215, 215, 215, 215, 215, 215, 215, 216, 216, 216, 216,
       216, 216, 217, 217, 217, 217, 217, 217, 218, 218, 218, 219, 219,
       219, 219, 220, 220, 220, 220, 220, 220, 220, 221, 221, 221, 221,
       221, 222, 222, 222, 222, 222, 223, 223, 224, 224, 225, 225, 226,
       228, 228, 228, 228, 229, 230, 230, 230, 230, 230, 230, 231],
      dtype=int32)), (np.float64(13.750127577481761), np.float64(201.0735294117647), np.float64(0.9745733646748277)))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Q-Q Plot of Flipper Length in the Training Set"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Theoretical quantiles"</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Sample quantiles"</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="chapter2-one-pop_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The Q-Q plot also suggests that the flipper length distribution is not perfectly normal. The points deviate from the reference line, especially in the lower and upper tails. This is consistent with what we observed in the histogram. However, the one-sample <code>t-test</code> is generally robust for moderate to large sample sizes, especially when there are no extreme outliers.</p>
<p>Finally, because penguin species differ in their physical measurements, we examine flipper length by species. This is not part of the formal one-sample test, but it helps us understand the structure of the data and why stratifying the train-test split by species was useful.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">train_set</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">species</span>, y <span class="op">=</span> <span class="va">flipper_length_mm</span>, fill <span class="op">=</span> <span class="va">species</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Flipper Length by Species in the Training Set"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Species"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Flipper length (mm)"</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_fill_brewer</span><span class="op">(</span>palette <span class="op">=</span> <span class="st">"Set2"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="chapter2-one-pop_files/figure-html/unnamed-chunk-12-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>species_order <span class="op">=</span> [<span class="st">"Adelie"</span>, <span class="st">"Chinstrap"</span>, <span class="st">"Gentoo"</span>]</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>sns.boxplot(</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>train_set,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"species"</span>,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">"flipper_length_mm"</span>,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    hue<span class="op">=</span><span class="st">"species"</span>,</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>    order<span class="op">=</span>species_order,</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>    hue_order<span class="op">=</span>species_order,</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>    palette<span class="op">=</span><span class="st">"Set2"</span>,</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>    legend<span class="op">=</span><span class="va">False</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Flipper Length by Species in the Training Set"</span>)</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Species"</span>)</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Flipper length (mm)"</span>)</span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="chapter2-one-pop_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The boxplots show that flipper length differs noticeably by species. Gentoo penguins tend to have longer flippers than Adelie and Chinstrap penguins, while Adelie penguins tend to have the shortest flippers among the three species. This helps explain why the overall distribution of flipper length is not perfectly normal: the full sample combines penguins from species with different typical flipper lengths.</p>
<p>Overall, the exploratory analysis shows that flipper length has a meaningful species structure and is not perfectly normally distributed. However, because the training and test sets have similar species proportions and the sample size is reasonably large, the one-sample <code>t-test</code> remains a reasonable first approach for testing the average flipper length in the broader penguin population represented by these data. The formal test will be conducted on the test set to keep the exploratory and inferential parts of the analysis separate.</p>
</section><section id="testing-settings" class="level3" data-number="2.1.5"><h3 data-number="2.1.5" class="anchored" data-anchor-id="testing-settings">
<span class="header-section-number">2.1.5</span> Testing Settings</h3>
<p>Before writing the hypotheses, we summarize the testing setup for this example. The response variable is <code>flipper_length_mm</code>, which is a quantitative variable measured in millimetres. The parameter of interest is the population mean flipper length, denoted by <span class="math inline">\(\mu\)</span>.</p>
<p>In this example, we compare the population mean flipper length to the reference value</p>
<p><span class="math display">\[
\mu_0 = 200.
\]</span></p>
<p>Since the population standard deviation is unknown, we use the sample standard deviation to estimate it. Therefore, the appropriate test is a one-sample <code>t-test</code>.</p>
<p>The formal test will be conducted using the test set. This keeps the exploratory analysis and the hypothesis test separate: the training set was used to understand the data, while the test set is used to calculate the test statistic and p-value.</p>
<p>For this test, we use:</p>
<ul>
<li>
<strong>Response variable:</strong> <code>flipper_length_mm</code>
</li>
<li>
<strong>Parameter of interest:</strong> <span class="math inline">\(\mu\)</span>, the population mean flipper length</li>
<li>
<strong>Reference value:</strong> <span class="math inline">\(\mu_0 = 200\)</span>
</li>
<li>
<strong>Test:</strong> one-sample <code>t-test</code>
</li>
<li>
<strong>Population variance:</strong> unknown</li>
<li>
<strong>Sample used for inference:</strong> <code>test_set</code>
</li>
<li>
<strong>Significance level:</strong> <span class="math inline">\(\alpha = 0.05\)</span>
</li>
</ul>
<p>Because this is a one-sample <code>t-test</code>, we assume that the observations are independent and that the sampling distribution of the sample mean is approximately normal. The exploratory analysis suggested that the raw flipper length distribution is not perfectly normal, partly because penguin species differ in their typical flipper lengths. However, the sample size is reasonably large and there are no severe outliers, so using the one-sample <code>t-test</code> is still a reasonable approach for this example.</p>
</section><section id="hypothesis-definitions" class="level3" data-number="2.1.6"><h3 data-number="2.1.6" class="anchored" data-anchor-id="hypothesis-definitions">
<span class="header-section-number">2.1.6</span> Hypothesis Definitions</h3>
<p>We now translate the research question into formal statistical hypotheses. Recall that <span class="math inline">\(\mu\)</span> denotes the population mean flipper length of penguins, and the reference value is</p>
<p><span class="math display">\[
\mu_0 = 200.
\]</span></p>
<p>Since the research question asks whether the population mean flipper length is <strong>different from</strong> 200 mm, we use a two-sided test.</p>
<p>The hypotheses are:</p>
<p><span class="math display">\[H_0: \mu = 200 \quad vs \quad H_a: \mu \neq 200\]</span></p>
<p>The null hypothesis states that the population mean flipper length is 200 mm. Under this hypothesis, any difference between the sample mean and 200 mm is attributed to random sampling variation.</p>
<p>The alternative hypothesis states that the population mean flipper length is not 200 mm. This includes both possibilities: the population mean could be less than 200 mm or greater than 200 mm.</p>
<p>In words, we are testing whether the test-set data provide sufficient evidence that the average flipper length in the broader penguin population represented by these data differs from 200 mm.</p>
</section><section id="test-flavour-and-components" class="level3" data-number="2.1.7"><h3 data-number="2.1.7" class="anchored" data-anchor-id="test-flavour-and-components">
<span class="header-section-number">2.1.7</span> Test Flavour and Components</h3>
<p>The one-sample <code>t-test</code> compares the sample mean to the hypothesized population mean. In this example, the hypothesized value is <span class="math inline">\(\mu_0 = 200\)</span> mm. Let <span class="math inline">\(\bar{x}\)</span> denotes the sample mean flipper length in the test set, and let <span class="math inline">\(s\)</span> denotes the sample standard deviation of flipper length in the test set. If the test set contains <span class="math inline">\(n\)</span> penguins, the test statistic is</p>
<p><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}}.
\]</span></p>
<p>In this formula:</p>
<ul>
<li>
<span class="math inline">\(\bar{x}\)</span> is the sample mean flipper length.</li>
<li>
<span class="math inline">\(\mu_0\)</span> is the hypothesized population mean, which is 200 mm in this example.</li>
<li>
<span class="math inline">\(s\)</span> is the sample standard deviation.</li>
<li>
<span class="math inline">\(n\)</span> is the sample size.</li>
<li>
<span class="math inline">\(s / \sqrt{n}\)</span> is the estimated standard error of the sample mean.</li>
</ul>
<p>The numerator, <span class="math inline">\(\bar{x} - \mu_0\)</span>, measures how far the sample mean is from the hypothesized value. The denominator, <span class="math inline">\(s / \sqrt{n}\)</span>, scales this difference by the estimated variability of the sample mean. Therefore, the test statistic measures how many estimated standard errors the sample mean is away from the hypothesized value.</p>
<p>Because the population standard deviation is unknown, we estimate it using the sample standard deviation <span class="math inline">\(s\)</span>. Under the null hypothesis, <span class="math inline">\(H_0: \mu = 200\)</span>, the test statistic follows a <code>t-distribution</code> with <span class="math inline">\(n-1\)</span> degrees of freedom. Since our alternative hypothesis is two-sided, i.e.&nbsp;<span class="math inline">\(H_A: \mu \neq 200\)</span> the p-value measures the probability of observing a test statistic at least as extreme as the one obtained from the data, in either direction, assuming that the null hypothesis is true.</p>
<p>At the significance level <span class="math inline">\(\alpha = 0.05\)</span>, we reject the null hypothesis if the p-value is less than 0.05. Otherwise, we do not reject the null hypothesis.</p>
</section><section id="inferential-conclusions" class="level3" data-number="2.1.8"><h3 data-number="2.1.8" class="anchored" data-anchor-id="inferential-conclusions">
<span class="header-section-number">2.1.8</span> Inferential Conclusions</h3>
<p>The goal of the one-sample <code>t-test</code> is to decide whether the observed sample mean is far enough from the hypothesized value to provide evidence against the null hypothesis. In this example, the null and alternative hypotheses are:</p>
<p><span class="math display">\[
H_0: \mu = 200 \quad \textit{vs} \quad H_a: \mu \neq 200
\]</span> where <span class="math inline">\(\mu\)</span> denotes the population mean flipper length of penguins. The hypothesized value is 200 mm. After computing the test statistic and p-value, we compare the p-value to the significance level <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p>If the p-value is less than 0.05, we reject the null hypothesis. In that case, we conclude that the data provide sufficient evidence that the population mean flipper length is different from 200 mm.</p>
<p>If the p-value is greater than or equal to 0.05, we do not reject the null hypothesis. In that case, we conclude that the data do not provide sufficient evidence that the population mean flipper length is different from 200 mm.</p>
<p>It is important to phrase the second conclusion carefully. Failing to reject the null hypothesis does not prove that the population mean is exactly 200 mm. It only means that, based on the available sample, we do not have enough evidence to conclude that it differs from 200 mm.</p>
</section><section id="how-to-run-the-test-in-r-and-python" class="level3" data-number="2.1.9"><h3 data-number="2.1.9" class="anchored" data-anchor-id="how-to-run-the-test-in-r-and-python">
<span class="header-section-number">2.1.9</span> How to run the test in R and Python?</h3>
<p>We now conduct the formal one-sample <code>t-test</code> using the test set. Recall that the training set was used for exploratory data analysis, while the test set is reserved for the formal hypothesis test. The test compares the sample mean of <code>flipper_length_mm</code> to the hypothesized value <span class="math inline">\(\mu_0 = 200\)</span>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">t_test_result</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span></span>
<span>  <span class="va">test_set</span><span class="op">$</span><span class="va">flipper_length_mm</span>,</span>
<span>  mu <span class="op">=</span> <span class="fl">200</span>,</span>
<span>  alternative <span class="op">=</span> <span class="st">"two.sided"</span>,</span>
<span>  conf.level <span class="op">=</span> <span class="fl">0.95</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">t_test_result</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  test_set$flipper_length_mm
t = 0.17512, df = 69, p-value = 0.8615
alternative hypothesis: true mean is not equal to 200
95 percent confidence interval:
 196.8825 203.7175
sample estimates:
mean of x 
    200.3 </code></pre>
</div>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the response variable from the R-created test set</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>flipper_test <span class="op">=</span> test_set[<span class="st">"flipper_length_mm"</span>]</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Hypothesized population mean</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>mu_0 <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a><span class="co"># One-sample t-test</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>t_stat, p_value <span class="op">=</span> stats.ttest_1samp(</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>    flipper_test,</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>    popmean<span class="op">=</span>mu_0,</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>    alternative<span class="op">=</span><span class="st">"two-sided"</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample size and degrees of freedom</span></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(flipper_test)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> n <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample mean and sample standard deviation</span></span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="op">=</span> flipper_test.mean()</span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>sample_sd <span class="op">=</span> flipper_test.std(ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard error</span></span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>standard_error <span class="op">=</span> sample_sd <span class="op">/</span> np.sqrt(n)</span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% confidence interval for the population mean</span></span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a>confidence_level <span class="op">=</span> <span class="fl">0.95</span></span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> confidence_level</span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a>t_critical <span class="op">=</span> stats.t.ppf(<span class="dv">1</span> <span class="op">-</span> alpha <span class="op">/</span> <span class="dv">2</span>, df)</span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-33"><a href="#cb47-33" aria-hidden="true" tabindex="-1"></a>ci_lower <span class="op">=</span> sample_mean <span class="op">-</span> t_critical <span class="op">*</span> standard_error</span>
<span id="cb47-34"><a href="#cb47-34" aria-hidden="true" tabindex="-1"></a>ci_upper <span class="op">=</span> sample_mean <span class="op">+</span> t_critical <span class="op">*</span> standard_error</span>
<span id="cb47-35"><a href="#cb47-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-36"><a href="#cb47-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample mean: </span><span class="sc">{</span>sample_mean<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample mean: 200.300</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample standard deviation: </span><span class="sc">{</span>sample_sd<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample standard deviation: 14.333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample size: </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample size: 70</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Degrees of freedom: </span><span class="sc">{</span>df<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Degrees of freedom: 69</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t-statistic: </span><span class="sc">{</span>t_stat<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>t-statistic: 0.175</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value: </span><span class="sc">{</span>p_value<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>p-value: 0.8615</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% confidence interval: (</span><span class="sc">{</span>ci_lower<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>ci_upper<span class="sc">:.3f}</span><span class="ss">)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>95% confidence interval: (196.882, 203.718)</code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>Details about <code>R</code> code and output</strong></p>
<p>In order to run this test in <code>R</code>, we use the <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> function. This function can be used to perform both one-sample and two-sample <code>t-tests</code>. In this section, we use it for a one-sample test because we are comparing one sample mean to a fixed hypothesized value.</p>
<p>The relevant arguments are as follows:</p>
<ul>
<li><p><code>x</code> is the numeric vector of observed data values. In this example, <code>x</code> is <code>test_set$flipper_length_mm</code>.</p></li>
<li><p><code>mu</code> is the hypothesized population mean under the null hypothesis. In this example, we set <code>mu = 200</code> because we are testing whether the population mean flipper length differs from 200 mm.</p></li>
<li><p><code>alternative</code> specifies the direction of the alternative hypothesis. We use <code>alternative = "two.sided"</code> because our alternative hypothesis is <span class="math inline">\(H_A: \mu \neq 200\)</span>.</p></li>
<li><p><code>conf.level</code> specifies the confidence level for the confidence interval. We use <code>conf.level = 0.95</code>, which gives a 95% confidence interval for the population mean.</p></li>
</ul>
<p>The output from <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> includes the test statistic, degrees of freedom, p-value, alternative hypothesis, confidence interval, and sample mean. The p-value is used to decide whether to reject the null hypothesis at the chosen significance level. The confidence interval gives a range of plausible values for the population mean flipper length.</p>
<p><strong>Details about <code>Python</code> code and output</strong></p>
<p>In <code>Python</code>, we use the <code>ttest_1samp()</code> function from the <code>scipy.stats</code> module. This function performs a one-sample <code>t-test</code> by comparing a sample mean to a hypothesized population mean.</p>
<p>The relevant arguments are:</p>
<ul>
<li><p>The first argument is the numeric vector of observed data values. In this example, we use <code>flipper_test</code>, which contains the <code>flipper_length_mm</code> values from the test set.</p></li>
<li><p><code>popmean</code> is the hypothesized population mean under the null hypothesis. In this example, we set <code>popmean = 200</code>.</p></li>
<li><p><code>alternative</code> specifies the direction of the alternative hypothesis. We use <code>alternative = "two-sided"</code> because we are testing whether the population mean is different from 200 mm.</p></li>
</ul>
<p>The <code>ttest_1samp()</code> function returns the test statistic and p-value. Unlike the <code>R</code> function <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code>, it does not automatically print the sample mean, degrees of freedom, standard deviation, or confidence interval in the same formatted output. For this reason, we calculate these quantities manually in the Python code.</p>
<p>The output gives the test statistic, degrees of freedom, p-value, and a 95% confidence interval for the population mean flipper length. These values will be used to decide whether the test set provides sufficient evidence that the population mean flipper length differs from 200 mm.</p>
</section><section id="storytelling" class="level3" data-number="2.1.10"><h3 data-number="2.1.10" class="anchored" data-anchor-id="storytelling">
<span class="header-section-number">2.1.10</span> Storytelling</h3>
<p>Based on the test set, the average flipper length is 200.3 mm, which is very close to the hypothesized value of 200 mm. The one-sample <code>t-test</code> gives a test statistic of 0.175 and a p-value of 0.8615.</p>
<p>Since the p-value is much larger than the significance level <span class="math inline">\(\alpha = 0.05\)</span>, we do not reject the null hypothesis. In other words, the test set does not provide sufficient evidence that the population mean flipper length differs from 200 mm.</p>
<p>The 95% confidence interval for the population mean flipper length is <span class="math inline">\((196.88,\ 203.72).\)</span> This interval includes 200 mm, which is consistent with the hypothesis test result. Based on these data, an average flipper length of 200 mm is a plausible value for the broader penguin population represented by this sample.</p>
<p>In plain language, the observed average flipper length is not significantly different from 200 mm, and the small difference between 200.3 mm and 200 mm can reasonably be explained by random sampling variation.</p>
</section></section><section id="one-sample-z-test-for-the-mean" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="one-sample-z-test-for-the-mean">
<span class="header-section-number">2.2</span> One-sample z-test for the mean</h2>
<section id="review-1" class="level3" data-number="2.2.1"><h3 data-number="2.2.1" class="anchored" data-anchor-id="review-1">
<span class="header-section-number">2.2.1</span> Review</h3>
<p>We use this test when: - The population variance <strong>σ² is known</strong>, and - The sample comes from a <strong>normally distributed population</strong>, or the <strong>sample size is large</strong> (typically ( n )).</p>
<p>The test statistic is:</p>
<p><span class="math display">\[ z = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}} \]</span></p>
<p>Where: - ( <span class="math inline">\(\bar{x}\)</span> ) is the sample mean<br>
- ( <span class="math inline">\(\mu_0\)</span> ) is the hypothesized population mean<br>
- ( <span class="math inline">\(\sigma\)</span> ) is the known population standard deviation<br>
- ( n ) is the sample size</p>
<p>We compare the calculated ( z )-value to a standard normal distribution to compute a p-value or make a decision based on a critical value.</p>
<p>Let’s revisit the earlier scenario: you want to assess whether a new method of teaching introductory physics at the University of British Columbia (UBC) improves student performance compared to historical results. This time, assume that the population standard deviation is known from previous years of large-scale data collection. This allows us to use a z-test. Suppose the average physics score in the population is: $$</p>
<p>μ(mean physics score at UBC)</p>
<p>$$</p>
<p><span class="math display">\[
\mu \quad \text{(mean physics score at UBC)}
\]</span> And we collect a <strong>random sample</strong> of <span class="math inline">\(n\)</span> students, recording their scores:</p>
<p><span class="math display">\[
X1,X2,…,XnX_1, X_2, \dots, X_n
\]</span></p>
<p>The Key question becomes:</p>
<blockquote class="blockquote">
<p><strong>Is the sample mean statistically different from a known reference value?</strong></p>
</blockquote>
<p>If, for example, the historical average physics score is known to be <strong>75</strong>, then our question becomes more specific:</p>
<blockquote class="blockquote">
<p><strong>Is the mean physics score in the sample statistically different from 75?</strong></p>
</blockquote>
</section><section id="study-design-1" class="level3" data-number="2.2.2"><h3 data-number="2.2.2" class="anchored" data-anchor-id="study-design-1">
<span class="header-section-number">2.2.2</span> Study Design</h3>
<p>We again use the <strong>Palmer Station Penguins</strong> dataset collected by the LTER in Antarctica (2007 – 2009).<br>
It includes measurements such as <em>flipper length</em>, <em>bill size</em>, and <em>body mass</em> across three penguin species.</p>
<blockquote class="blockquote">
<p><strong>Research question:</strong><br><em>Is the average flipper length of penguins significantly different from 200 mm, assuming a known population standard deviation?</em></p>
</blockquote>
<hr></section><section id="data-collection-wrangling" class="level3" data-number="2.2.3"><h3 data-number="2.2.3" class="anchored" data-anchor-id="data-collection-wrangling">
<span class="header-section-number">2.2.3</span> Data Collection &amp; Wrangling</h3>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<div class="cell">
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://allisonhorst.github.io/palmerpenguins/">palmerpenguins</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span></span>
<span><span class="va">penguins_clean</span> <span class="op">&lt;-</span> <span class="va">penguins</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">train_index</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">penguins_clean</span><span class="op">)</span><span class="op">)</span>, </span>
<span>                      size <span class="op">=</span> <span class="fl">0.8</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">penguins_clean</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">train_set</span> <span class="op">&lt;-</span> <span class="va">penguins_clean</span><span class="op">[</span><span class="va">train_index</span>, <span class="op">]</span></span>
<span><span class="va">test_set</span> <span class="op">&lt;-</span> <span class="va">penguins_clean</span><span class="op">[</span><span class="op">-</span><span class="va">train_index</span>, <span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load dataset</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>penguins <span class="op">=</span> sns.load_dataset(<span class="st">"penguins"</span>)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>penguins_clean <span class="op">=</span> penguins.dropna()</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>train_set, test_set <span class="op">=</span> train_test_split(</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>    penguins_clean, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="exploratory-data-analysis-eda-1" class="level3" data-number="2.2.4"><h3 data-number="2.2.4" class="anchored" data-anchor-id="exploratory-data-analysis-eda-1">
<span class="header-section-number">2.2.4</span> Exploratory Data Analysis (EDA)</h3>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<div class="cell">
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">train_set</span><span class="op">$</span><span class="va">flipper_length_mm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  172.0   190.0   198.0   201.5   214.0   231.0 </code></pre>
</div>
</div>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(train_set[<span class="st">"flipper_length_mm"</span>].describe())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>count    266.00000
mean     201.00000
std       13.91592
min      172.00000
25%      190.00000
50%      197.00000
75%      213.00000
max      231.00000
Name: flipper_length_mm, dtype: float64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>train_set[<span class="st">"flipper_length_mm"</span>].hist(edgecolor<span class="op">=</span><span class="st">"black"</span>, color<span class="op">=</span><span class="st">"skyblue"</span>)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of Flipper Length (mm)"</span>)</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Flipper Length (mm)"</span>)</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="chapter2-one-pop_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>plt.scatter(</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>    train_set[<span class="st">"body_mass_g"</span>],</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>    train_set[<span class="st">"flipper_length_mm"</span>],</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.6</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Body Mass vs. Flipper Length"</span>)</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Body Mass (g)"</span>)</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Flipper Length (mm)"</span>)</span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="chapter2-one-pop_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="testing-settings-1" class="level3" data-number="2.2.5"><h3 data-number="2.2.5" class="anchored" data-anchor-id="testing-settings-1">
<span class="header-section-number">2.2.5</span> Testing Settings</h3>
<p>We use a significant level of to run the test.</p>
</section><section id="hypotheses" class="level3" data-number="2.2.6"><h3 data-number="2.2.6" class="anchored" data-anchor-id="hypotheses">
<span class="header-section-number">2.2.6</span> Hypotheses</h3>
<p>We can formally express this with the following hypotheses:</p>
<ul>
<li>
<strong>Null hypothesis</strong> <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = 75\)</span>
</li>
<li>
<strong>Alternative hypothesis</strong> <span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu \ne 75\)</span>
</li>
</ul>
<p>Under the null hypothesis, we assume that the new teaching method does not significantly change the average score. If the null is rejected, we infer that the method may lead to <strong>higher or lower</strong> performance.</p>
</section><section id="test-flavour-and-components-1" class="level3" data-number="2.2.7"><h3 data-number="2.2.7" class="anchored" data-anchor-id="test-flavour-and-components-1">
<span class="header-section-number">2.2.7</span> Test Flavour and Components</h3>
<p>The test statistic is:</p>
<p><span class="math display">\[z=xˉ−μ0σ/nz = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}}\]</span></p>
<p>Where: • <span class="math inline">\(\bar{x}\)</span> is the sample mean</p>
<p>• <span class="math inline">\(\mu_0\)</span> is the reference value (e.g., 75)</p>
<p>• <span class="math inline">\(\sigma\)</span> is the known population standard deviation • <span class="math inline">\(n\)</span> is the sample size</p>
<p>This statistic follows a <strong>standard normal distribution</strong> (<span class="math inline">\(\mathcal{N}(0, 1)\)</span>)..</p>
</section><section id="inferential-conclusions-1" class="level3" data-number="2.2.8"><h3 data-number="2.2.8" class="anchored" data-anchor-id="inferential-conclusions-1">
<span class="header-section-number">2.2.8</span> Inferential Conclusions</h3>
<p>The z-test typically results in a slightly smaller p-value than the t-test because the z-distribution has “thinner tails” than the t-distribution.</p>
</section><section id="how-to-run-the-test-in-r-and-python-1" class="level3" data-number="2.2.9"><h3 data-number="2.2.9" class="anchored" data-anchor-id="how-to-run-the-test-in-r-and-python-1">
<span class="header-section-number">2.2.9</span> How to run the test in R and Python?</h3>
</section><section id="storytelling-1" class="level3" data-number="2.2.10"><h3 data-number="2.2.10" class="anchored" data-anchor-id="storytelling-1">
<span class="header-section-number">2.2.10</span> Storytelling</h3>
<p>Rejecting the null here provides high confidence that the population mean has shifted from 200 mm, assuming our historical <span class="math inline">\(\sigma\)</span> is still accurate.</p>
</section></section><section id="one-sample-z-test-for-proportions" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="one-sample-z-test-for-proportions">
<span class="header-section-number">2.3</span> One-sample z-test for proportions</h2>
<section id="review-2" class="level3" data-number="2.3.1"><h3 data-number="2.3.1" class="anchored" data-anchor-id="review-2">
<span class="header-section-number">2.3.1</span> Review</h3>
<p>Use this test when: - The variable is <strong>binary</strong> (success/failure, yes/no, etc.), and - You want to test a <strong>population proportion</strong> ( p ), using a large enough sample.</p>
<p>The test statistic is:</p>
<p><span class="math display">\[z = \frac{\hat{p} - p_0}{\sqrt{p_0(1 - p_0)/n}}\]</span></p>
<p>Where: - ( <span class="math inline">\(\hat{p}\)</span> ) is the sample proportion<br>
- ( <span class="math inline">\(p_0\)</span> ) is the hypothesized population proportion<br>
- ( <span class="math inline">\(n\)</span> ) is the sample size</p>
<p>Just like the one-sample t-test is used to assess differences in means, the <strong>one-sample z-test</strong> is used when: • You are working with <strong>proportions</strong> (e.g., fraction of penguins with a specific characteristic), • The sample size is <strong>sufficiently large</strong> to justify using the normal approximation. This test is ideal for binary outcomes: for example, whether a penguin is <strong>of the Adelie species or not</strong>. Suppose you want to test whether the <strong>proportion of Adelie penguins</strong> in your sample differs from a historically established value. Let’s say historical records suggest that <strong>45% of penguins</strong> in a certain region were Adelie. You want to know whether the proportion in your current sample is <strong>statistically different from 0.45</strong>.</p>
<p>The central question becomes: &gt; ** Is the proportion of Adelie penguins in the sample different from 0.45?? <strong>We are again working with the</strong> Palmer Station Penguins** dataset.</p>
</section><section id="study-design-2" class="level3" data-number="2.3.2"><h3 data-number="2.3.2" class="anchored" data-anchor-id="study-design-2">
<span class="header-section-number">2.3.2</span> Study Design</h3>
<p>Once again, we turn to the <strong>Palmer Station Penguins</strong> dataset, which includes species information for each penguin observed.</p>
<blockquote class="blockquote">
<p><strong>Research question:</strong><br>
* Is the proportion of Adelie penguins in the training dataset significantly different from 45%?**</p>
</blockquote>
<hr></section><section id="data-collection-wrangling-1" class="level3" data-number="2.3.3"><h3 data-number="2.3.3" class="anchored" data-anchor-id="data-collection-wrangling-1">
<span class="header-section-number">2.3.3</span> Data Collection &amp; Wrangling</h3>
<p>We continue with the same cleaned and split dataset from the earlier section.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<div class="cell">
<div class="sourceCode" id="cb69"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">train_set</span><span class="op">$</span><span class="va">is_adelie</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">train_set</span><span class="op">$</span><span class="va">species</span> <span class="op">==</span> <span class="st">"Adelie"</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">train_set</span><span class="op">)</span></span>
<span><span class="va">num_adelie</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">train_set</span><span class="op">$</span><span class="va">is_adelie</span><span class="op">)</span></span>
<span><span class="va">p_hat</span> <span class="op">&lt;-</span> <span class="va">num_adelie</span> <span class="op">/</span> <span class="va">n</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Sample size:"</span>, <span class="va">n</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample size: 266 </code></pre>
</div>
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Number of Adelie penguins:"</span>, <span class="va">num_adelie</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of Adelie penguins: 113 </code></pre>
</div>
<div class="sourceCode" id="cb73"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Sample proportion:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">p_hat</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample proportion: 0.425 </code></pre>
</div>
</div>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a binary column: 1 if Adelie, 0 otherwise</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>train_set[<span class="st">"is_adelie"</span>] <span class="op">=</span> (train_set[<span class="st">"species"</span>] <span class="op">==</span> <span class="st">"Adelie"</span>).astype(<span class="bu">int</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Total number of observations</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> train_set.shape[<span class="dv">0</span>]</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of Adelie penguins</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>num_adelie <span class="op">=</span> train_set[<span class="st">"is_adelie"</span>].<span class="bu">sum</span>() </span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample proportion</span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>p_hat <span class="op">=</span> num_adelie <span class="op">/</span> n</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample size: </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample size: 266</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of Adelie penguins: </span><span class="sc">{</span>num_adelie<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of Adelie penguins: 115</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample proportion: </span><span class="sc">{</span>p_hat<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample proportion: 0.432</code></pre>
</div>
</div>
</div>
</div>
</div>
</section><section id="exploratory-data-analysis-eda-2" class="level3" data-number="2.3.4"><h3 data-number="2.3.4" class="anchored" data-anchor-id="exploratory-data-analysis-eda-2">
<span class="header-section-number">2.3.4</span> Exploratory Data Analysis (EDA)</h3>
<p>Let’s visualize the distribution of penguin species in our training sample.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-11-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-1" role="tab" aria-controls="tabset-11-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-11-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-2" role="tab" aria-controls="tabset-11-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-11-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-11-1-tab">
<div class="cell">
<div class="sourceCode" id="cb81"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">train_set</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">species</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"orange"</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Penguin Species Count in Training Set"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"Species"</span>, y <span class="op">=</span> <span class="st">"Count"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="chapter2-one-pop_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-11-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-11-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>train_set[<span class="st">"species"</span>].value_counts().plot(</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>kind<span class="op">=</span><span class="st">"bar"</span>, color<span class="op">=</span><span class="st">"orange"</span>, edgecolor<span class="op">=</span><span class="st">"black"</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Penguin Species Count in Training Set"</span>)</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Count"</span>)</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Species"</span>)</span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(array([0, 1, 2]), [Text(0, 0, 'Adelie'), Text(1, 0, 'Gentoo'), Text(2, 0, 'Chinstrap')])</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="chapter2-one-pop_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="hypotheses-1" class="level3" data-number="2.3.5"><h3 data-number="2.3.5" class="anchored" data-anchor-id="hypotheses-1">
<span class="header-section-number">2.3.5</span> Hypotheses</h3>
<p>We can formally express this with the following hypotheses:</p>
<ul>
<li>
<strong>Null hypothesis</strong> <span class="math inline">\(H_0\)</span>: <span class="math inline">\(p = 0.45\)</span>
</li>
<li>
<strong>Alternative hypothesis</strong> <span class="math inline">\(H_1\)</span>: <span class="math inline">\(p \ne 0.45\)</span> Where: • <span class="math inline">\(p\)</span> is the true proportion of Adelie penguins in the population. We will estimate <span class="math inline">\(p\)</span> using <span class="math inline">\(\hat{p}\)</span>, the sample proportion of Adelie penguins. The test statistic is:</li>
</ul>
<p><span class="math display">\[z = \frac{\hat{p} - p_0}{\sqrt{p_0(1 - p_0)/n}}\]</span></p>
<p>Where: - ( <span class="math inline">\(\hat{p}\)</span> ) is the sample proportion<br>
- ( <span class="math inline">\(p_0\)</span> ) is the hypothesized population proportion<br>
- ( <span class="math inline">\(n\)</span> ) is the sample size</p>
<p>This follows a <strong>standard normal distribution</strong> (<span class="math inline">\(z\)</span>-distribution) under the null hypothesis.</p>
</section><section id="how-to-run-the-test-in-r-and-python-2" class="level3" data-number="2.3.6"><h3 data-number="2.3.6" class="anchored" data-anchor-id="how-to-run-the-test-in-r-and-python-2">
<span class="header-section-number">2.3.6</span> How to run the test in R and Python</h3>
<p>Now we perform the z-test for one proportion. Assuming a historical reference proportion of 0.45 for Adelie penguins:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-12-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-1" role="tab" aria-controls="tabset-12-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-12-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-2" role="tab" aria-controls="tabset-12-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-12-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-12-1-tab">
<div class="cell">
<div class="sourceCode" id="cb85"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p0</span> <span class="op">&lt;-</span> <span class="fl">0.45</span></span>
<span><span class="va">se</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">p0</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">p0</span><span class="op">)</span> <span class="op">/</span> <span class="va">n</span><span class="op">)</span></span>
<span><span class="va">z_stat</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">p_hat</span> <span class="op">-</span> <span class="va">p0</span><span class="op">)</span> <span class="op">/</span> <span class="va">se</span></span>
<span><span class="va">p_value</span> <span class="op">&lt;-</span> <span class="fl">2</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">z_stat</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"z ="</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">z_stat</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">", p ="</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">p_value</span>, <span class="fl">4</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>z = -0.826 , p = 0.4089 </code></pre>
</div>
</div>
</div>
<div id="tabset-12-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-12-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Reference proportion</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>p0 <span class="op">=</span> <span class="fl">0.45</span></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample proportion</span></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>p_hat <span class="op">=</span> num_adelie <span class="op">/</span> n</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard error under H0</span></span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> np.sqrt(p0 <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p0) <span class="op">/</span> n)</span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a><span class="co"># z-statistic</span></span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>z_stat <span class="op">=</span> (p_hat <span class="op">-</span> p0) <span class="op">/</span> se</span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-tailed p-value</span></span>
<span id="cb87-12"><a href="#cb87-12" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.norm.cdf(<span class="bu">abs</span>(z_stat)))</span>
<span id="cb87-13"><a href="#cb87-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"z = </span><span class="sc">{</span>z_stat<span class="sc">:.3f}</span><span class="ss">, p = </span><span class="sc">{</span>p_value<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>z = -0.579, p = 0.5624</code></pre>
</div>
</div>
</div>
</div>
</div>
</section><section id="inferential-conclusions-2" class="level3" data-number="2.3.7"><h3 data-number="2.3.7" class="anchored" data-anchor-id="inferential-conclusions-2">
<span class="header-section-number">2.3.7</span> Inferential Conclusions</h3>
<p>A one-sample z-test for proportions was conducted to determine whether the proportion of female penguins differs significantly from 0.45. Based on the sample data, the test produced a z-statistic of z and a p-value of p.&nbsp;If we reject the null, it indicates the species composition in this region has shifted from historical records.</p>
</section><section id="storytelling-2" class="level3" data-number="2.3.8"><h3 data-number="2.3.8" class="anchored" data-anchor-id="storytelling-2">
<span class="header-section-number">2.3.8</span> Storytelling</h3>
<p>Given a significance level of 0.05, if the p-value is less than 0.05, we reject the null hypothesis and conclude that the proportion of female penguins is significantly different from 0.45. Otherwise, we do not have sufficient evidence to say it differs.</p>
<hr>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/pnickchi\.github\.io\/test-book\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
          // default icon
          link.classList.add("external");
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../book/chapter1-intro.html" class="pagination-link" aria-label="Introduction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../book/chapter3-two-pop.html" class="pagination-link" aria-label="Tests for Two Continuous Population Mean">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Tests for Two Continuous Population Mean</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026; G. Alexi Rodríguez-Arelis, Kate Manskaia, and Payman Nickchi.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/pnickchi/test-book/edit/main/book/chapter2-one-pop.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/pnickchi/test-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/pnickchi/test-book/blob/main/book/chapter2-one-pop.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>